app:
    resource: "@AppBundle/Controller/"
    type:     annotation

register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:index }

profile:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:index }